apiVersion: batch/v1
kind: Job
metadata:
  name: minio-create-artifact-bucket
  namespace: workflow-pipeline
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: create-bucket
          image: minio/mc:RELEASE.2024-07-15T17-46-06Z
          command:
            - /bin/sh
            - -c
            - |
              until mc alias set local http://minio:9000 "$OBJECT_STORAGE_ACCESS_KEY" "$OBJECT_STORAGE_SECRET_KEY"; do sleep 2; done
              mc mb --ignore-existing "local/$OBJECT_STORAGE_BUCKET"
          env:
            - name: OBJECT_STORAGE_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: workflow-config
                  key: OBJECT_STORAGE_BUCKET
            - name: OBJECT_STORAGE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: workflow-secrets
                  key: OBJECT_STORAGE_ACCESS_KEY
            - name: OBJECT_STORAGE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: workflow-secrets
                  key: OBJECT_STORAGE_SECRET_KEY
